### PR TITLE
bolt storage api

### PR DESCRIPTION
**Pull request by tammybutow**
Looks good!

### CODE REVIEW

**Comment by brendensoares** [comment]
We need more than a `master` branch on this repo so my tagging makes sense, lol.

Well, what can you tell us about this PR @tammybutow ?

**Comment by brendensoares** [comment]
I may be missing the obvious, but does one use the code in this PR? :confused:

**Comment by tammybutow** [comment]
wrong branch, will create a new one ~ the code is created duing the Women Who Go NYC hackathon that uses boltdb is here: https://github.com/womenwhogonyc/samples/blob/master/chat/app/chatroom/storage.go

**Comment by brendensoares** [comment]
How is the storage.go code consumed by the sample app?

PS - nice hackathon, do you guys have a website or any presentations? I could add the link to our [Articles](https://github.com/revel/revel/wiki/Articles) page if it mentions Revel :)

**Pull request closed without merging**
